### PR TITLE
initial appveyor.yml CI config

### PR DESCRIPTION
**Pull request by chcg**
- fixed debug build
- fixed v140 build

see https://ci.appveyor.com/project/chcg/nppgitscm/builds/23480713

### CODE REVIEW

**Comment by vinsworldcom** [comment]
Don't use appveyor, but did fix the VCXPROJ debug build optimization issue.

**Comment by chcg** [comment]
@vinsworldcom Would you accept a PR for a CI build via github action?

**Comment by vinsworldcom** [comment]
@chcg what does that do?  build the distribution ZIPs for me?  I don't use Github Actions so not familiar with it.  I could learn though if it helps.

**Comment by chcg** [comment]
See e.g. https://github.com/ashkulz/NppFTP/blob/master/.github/workflows/CI_build.yml used for

https://github.com/ashkulz/NppFTP/releases/tag/v0.29.8
built via
https://github.com/ashkulz/NppFTP/actions/runs/1599561834

**Comment by vinsworldcom** [comment]
Seems like it creates the Release for you?  I see Linux in there as well as a 'makefile' and CMake stuff - I don't use any of that, only MSBuild with .vcxproj files.  Does that matter?

**Comment by chcg** [comment]
MSBuild is also possible, see https://github.com/chcg/NPP_HexEdit/blob/master/.github/workflows/CI_build.yml.

See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners and https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md about the preinstalled SW on the available machines.

**Comment by vinsworldcom** [comment]
That seems simpler!  So just add the .github\workflows directory and CI_build.yml file?  Then when pushing to main branch, do I just need to create a `git tag ...` with the new version number before `git push ...` to kick off the release build?

**Pull request closed without merging**
